In [24]:
import numpy as np
import pandas as pd

In [25]:
data = pd.read_csv('customer.csv')
data.head()

   age  gender   review education purchased
0   41    Male  Average        UG       Yes
1   29  Female     Good        PG       Yes
2   63    Male     Poor    School        No
3   52  Female  Average        UG        No
4   21    Male     Good    School       Yes

In [26]:
df = data.iloc[: , 2:]
df.head()

    review education purchased
0  Average        UG       Yes
1     Good        PG       Yes
2     Poor    School        No
3  Average        UG        No
4     Good    School       Yes

In [27]:
x=df.iloc[:,:2]
y=df.iloc[: , -1]

from sklearn.model_selection import train_test_split
x_train , x_test , y_train , y_test = train_test_split(x , y , test_size = 0.2)

In [28]:
from sklearn.preprocessing import OrdinalEncoder
od = OrdinalEncoder(categories=[['Poor' , 'Average','Good'],['School' , 'UG','PG']])

In [29]:
x_train = od.fit_transform(x_train)
print(x_test,"\n\n\n")
x_test = od.transform(x_test)
x_test

     review education
71     Good        PG
85  Average        UG
42     Good        UG
18  Average        PG
3   Average        UG
23     Poor        UG
27  Average        PG
70  Average        UG
99     Poor    School
45     Good    School
60     Good        PG
76  Average        UG
82  Average        UG
94  Average        UG
90     Poor    School
19     Good    School
77     Good        PG
81     Poor    School
51     Good        PG
26     Poor        UG

array([[2., 2.],
       [1., 1.],
       [2., 1.],
       [1., 2.],
       [1., 1.],
       [0., 1.],
       [1., 2.],
       [1., 1.],
       [0., 0.],
       [2., 0.],
       [2., 2.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [0., 0.],
       [2., 0.],
       [2., 2.],
       [0., 0.],
       [2., 2.],
       [0., 1.]])

In [30]:
x_train[0:13]

array([[1., 0.],
       [2., 2.],
       [2., 2.],
       [1., 0.],
       [1., 1.],
       [0., 1.],
       [1., 2.],
       [1., 1.],
       [1., 2.],
       [1., 1.],
       [0., 0.],
       [2., 2.],
       [0., 1.]])

In [31]:
print()